# ===================================
# Filter Scope Definitions
# ===================================

scopes:

    trashed:
        label: "initbiz.cumuluscore::lang.trashed.filter_button"
        type: switch
        default: 0
        scope: applyTrashedFilter

    groups:
        label: rainlab.user::lang.group.label
        modelClass: RainLab\User\Models\UserGroup
        nameFrom: name
        scope: filterByGroup

    created_date:
        label: rainlab.user::lang.user.created_at
        type: daterange
        conditions: created_at >= ':after' AND created_at <= ':before'

    activated:
        label: rainlab.user::lang.user.status_activated
        type: switch
        conditions:
            - is_activated = '0'
            - is_activated = '1'
