scopes:
    trashed:
        label: "initbiz.cumuluscore::lang.trashed.filter_button"
        type: switch
        default: 0
        scope: applyTrashedFilter
    plan:
        label: "initbiz.cumuluscore::lang.cluster.plan_filter"
        scope: applyPlanFilter
        modelClass: Initbiz\CumulusCore\Models\Plan
        nameFrom: name
