name: Clusters
modelClass: Initbiz\CumulusCore\Models\Cluster
form: $/initbiz/cumuluscore/models/cluster/fields.yaml
defaultRedirect: initbiz/cumuluscore/clusters
create:
    redirect: 'initbiz/cumuluscore/clusters/update/:id'
    redirectClose: initbiz/cumuluscore/clusters
update:
    redirect: initbiz/cumuluscore/clusters
    redirectClose: initbiz/cumuluscore/clusters
preview: {  }
