name: initbiz.cumuluscore::lang.plan.plan
form: $/initbiz/cumuluscore/models/plan/fields.yaml
modelClass: Initbiz\CumulusCore\Models\Plan
defaultRedirect: initbiz/cumuluscore/plans
create:
    redirect: 'initbiz/cumuluscore/plans/update/:id'
    redirectClose: initbiz/cumuluscore/plans
update:
    redirect: initbiz/cumuluscore/plans
    redirectClose: initbiz/cumuluscore/plans
